# Generated by Django 3.2.5 on 2023-03-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230223_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cathegory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='pages.post'),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='pages.post'),
        ),
    ]
