# Generated by Django 3.2.5 on 2023-03-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20230317_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_cathegory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cathegory', to='pages.post'),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='pages.post'),
        ),
    ]
