# Generated by Django 3.2.5 on 2023-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230319_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
