# Generated by Django 3.2.5 on 2023-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_cathegory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='description',
            field=models.TextField(),
        ),
    ]
